public class UsernameToken {
        public String Username;
        public String Password;
        private String[] username_type_info = new String[]{'Username','http://Paymetric/XiPaySoap30/message/','string','1','1','false'};
        private String[] password_type_info = new String[]{'Password','http://Paymetric/XiPaySoap30/message/','string','1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://Paymetric/XiPaySoap30/message/','true','false'};
        private String[] field_order_type_info = new String[]{'username','password'};
}